version: "3.5"
services:
  api:
    build:
      context: ./Account.Service
      dockerfile: run.Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:80
    volumes:
      - ./Account.Service/src:/app
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    environment:
      SA_PASSWORD: "tsn3CgHMYr5jWYbE"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433